version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/env.example
    ports:
      - "4000:4000"
    volumes:
      - ./backend/data:/app/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: "http://localhost:4000"
    ports:
      - "8080:80"
    depends_on:
      - backend

