version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=4000
      - DATABASE_FILE=./backend/data/health_dashboard.sqlite
      - CORS_ORIGIN=*
      - SLACK_WEBHOOK_URL=
      - DEMO_MODE=true
      - EMAIL_FROM=hac.sank@gmail.com
      - EMAIL_TO=hac.sank@gmail.com
      - EMAIL_PASSWORD=vndj hwfc wttb hizt
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
    ports:
      - "4000:4000"
    volumes:
      - ./backend/data:/app/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: "http://localhost:4000"
    ports:
      - "8080:80"
    depends_on:
      - backend

